services:
  backend:
    build: ./Backend
    ports:
      - "8000:8000"
    volumes:
      - ./Backend:/app
      - ./models:/root/.insightface/models
      - ./images:/app/images
      - ./data:/app/data
      - ./output:/app/output
    environment:
      - IMAGES_DIR=/app/images
      - DATA_DIR=/app/data
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/facefindr
    depends_on:
      - db

  frontend:
    build: ./Frontend
    ports:
      - "5173:5173"
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=facefindr
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: